function ButtonColumn(a){this.canvas=a;this.canvas.controller=this;this.ctx=a.getContext("2d");this.buttons=[];var b=[new BCIcon({icon:"hdd",style:"white"}),new BCIcon({icon:"folder-open",style:"white"})],d=[["Save States"],["Best",null,b[1]],[this.getScoreForState("Best")],["1",b[0],b[1]],[this.getScoreForState("1")],["2",b[0],b[1]],[this.getScoreForState("2")]],c=[[""],["Best",null,function(){var a=localStorage.getItem(args.id+"-Best");a&&(a=JSON.parse(a),loadState(a))}],[],["1",function(){var a=
getCurrentState();localStorage.setItem(args.id+"-1",JSON.stringify(a));this.setScoreForState("1",a.score)},function(){var a=localStorage.getItem(args.id+"-1");a&&(a=JSON.parse(a),loadState(a))}],[],["2",function(){var a=getCurrentState();localStorage.setItem(args.id+"-2",JSON.stringify(a));this.setScoreForState("2",a.score)},function(){var a=localStorage.getItem(args.id+"-2");a&&(a=JSON.parse(a),loadState(a))}],[]],e;for(e in b)b[e].addListener("changed",function(){this.draw()},this);this.data=[];
for(e=0;e<d.length;e++){var f=e*G_H,b=[d[e][0]];d[e][1]?(button=new BCButton(~~(a.width-2*BC_BUTTON_W),~~(f+(G_H-BC_BUTTON_H)/2),d[e][1],BC_BUTTON_W,BC_BUTTON_H),this.buttons.push(button),b.push(button)):b.push(null);d[e][2]?(button=new BCButton(~~(a.width-BC_BUTTON_W),~~(f+(G_H-BC_BUTTON_H)/2),d[e][2],BC_BUTTON_W,BC_BUTTON_H),b.push(button),this.buttons.push(button)):b.push(null);this.data.push(b)}e=function(a){var b=$(this).offset(),d=a.pageX-b.left,b=a.pageY-b.top,c=!1,e;for(e in this.controller.buttons)d>
this.controller.buttons[e].x&&d<this.controller.buttons[e].x+this.controller.buttons[e].width&&b>this.controller.buttons[e].y&&b<this.controller.buttons[e].y+this.controller.buttons[e].height?(this.controller.buttons[e].setOver(!0)&&(c=!0),"mousedown"==a.type&&this.controller.buttons[e].setDown(!0)?c=!0:"mouseup"==a.type&&this.controller.buttons[e].setDown(!1)&&(c=!0),"mouseup"==a.type&&this.controller.buttons[e].fireEvent(new $.Event("clicked"))):this.controller.buttons[e].setOver(!1)&&(c=!0);c&&
this.controller.draw()};$(this.canvas).mousemove(e);$(this.canvas).mousedown(e);$(this.canvas).mouseup(e);$(this.canvas).mouseout(function(){var a=!1,b;for(b in this.controller.buttons)this.controller.buttons[b].setOver(!1)&&(a=!0),this.controller.buttons[b].setDown(!1)&&(a=!0);a&&this.controller.draw()});for(e=0;e<c.length;e++)for(a=0;a<c[e].length;a++)null!=this.data[e][a]&&("object"==typeof this.data[e][a]&&"function"==typeof c[e][a])&&this.data[e][a].addListener("clicked",c[e][a],this)}
ButtonColumn.prototype.setScoreForState=function(a,b){for(var d=0;d<this.data.length-1;d++)this.data[d][0]&&this.data[d][0]==a&&(this.data[d+1][0]=b);this.draw()};ButtonColumn.prototype.getScoreForState=function(a){return(a=localStorage.getItem(args.id+"-"+a))?(a=JSON.parse(a),a.score):null};
ButtonColumn.prototype.draw=function(){var a=this.ctx,b=this.canvas.width,d=this.canvas.height;a.save();a.setTransform(1,0,0,1,0,0);a.clearRect(0,0,b,d);a.restore();b=a.createLinearGradient(0,0,BC_BACKGROUND_GRID_W,0);b.addColorStop(0,G_COLOUR);b.addColorStop(1,G_COLOUR_A);a.strokeStyle=b;a.fillStyle=G_COLOUR;a.lineWidth=1;a.beginPath();for(b=0;b<=G_ROW;b++)a.moveTo(-0.5,b*G_H+0.5),a.lineTo(BC_BACKGROUND_GRID_W+0.5,b*G_H+0.5);a.closePath();a.stroke();a.font="10pt sans-serif";a.textBaseline="middle";
a.textAlign="left";for(b=0;b<this.data.length;b++)if(d=b*G_H,this.data[b][0]&&"string"==typeof this.data[b][0]?a.fillText(this.data[b][0],5,d+G_H/2):this.data[b][0]&&"number"==typeof this.data[b][0]&&(a.save(),a.font="8pt sans-serif",a.textAlign="right",a.textBaseline="top",a.fillText("Score: "+this.data[b][0],BC_W-BC_BUTTON_W/3,d),a.restore()),this.data[b][1]&&(a.save(),a.translate(this.data[b][1].x,this.data[b][1].y),this.data[b][1].draw(a),a.restore()),this.data[b][2])a.save(),a.translate(this.data[b][2].x,
this.data[b][2].y),this.data[b][2].draw(a),a.restore()};function BCButton(a,b,d,c,e){this.x=a;this.y=b;this.icon=d;this.width=c;this.height=e;this.listeners=[];this.over=!1}BCButton.prototype.fireEvent=function(a){a.target=this;for(var b in this.listeners[a.type])a.listenerId=b,this.listeners[a.type][b][0].call(this.listeners[a.type][b][1],a)};BCButton.prototype.setDown=function(a){return a!=this.down?(this.down=a,!0):!1};
BCButton.prototype.setOver=function(a){return a!=this.over?(this.over=a,!0):!1};BCButton.prototype.addListener=function(a,b,d){void 0===this.listeners[a]&&(this.listeners[a]=[]);this.listeners[a].push([b,d]);return this.listeners[a].length-1};BCButton.prototype.removeListener=function(a,b){delete this.listeners[a][b]};
BCButton.prototype.draw=function(a){a.clearRect(0,0,this.width,this.height);this.down?(a.fillStyle=BC_BUTTON_DOWN_COLOUR,a.fillRect(0,0,this.width,this.height)):this.over&&(a.fillStyle=BC_BUTTON_OVER_COLOUR,a.fillRect(0,0,this.width,this.height));if(this.icon&&this.icon.image){var b=~~((this.width-this.icon.width)/2),d=~~((this.height-this.icon.height)/2);a.drawImage(this.icon.image,this.icon.x,this.icon.y,this.icon.width,this.icon.height,0<=b?b:0,0<=d?d:0,this.icon.width,this.icon.height)}};
function BCIcon(a){BCIcon.inited||BCIcon.init();a.icon?(this.x=BCIcon.coords[a.icon].x,this.y=BCIcon.coords[a.icon].y):(this.x=a.x,this.y=a.y);this.style="undefined"!==typeof a.style?a.style:"black";this.image=BCIcon.images[this.style];this.height=this.width=14;this.listeners=[];BCIcon.allInstances.push(this)}BCIcon.imageSrcs={black:"img/glyphicons-halflings.png",white:"img/glyphicons-halflings-white.png"};
BCIcon.coords={download:{x:120,y:24},upload:{x:144,y:24},"folder-open":{x:408,y:120},hdd:{x:0,y:144}};BCIcon.images={};BCIcon.inited=!1;BCIcon.allInstances=[];
BCIcon.init=function(){BCIcon.inited=!0;for(var a in BCIcon.imageSrcs){var b=new Image;b.key=a;b.onload=function(){for(var a in BCIcon.allInstances)BCIcon.allInstances[a].style==this.key&&(BCIcon.allInstances[a].image=this,BCIcon.allInstances[a].fireEvent(new $.Event("changed")))};b.onerror=function(){console.log("error loading BCIcon: "+this.key)};b.src=BCIcon.imageSrcs[a];BCIcon.images[a]=b}};BCIcon.prototype.changeStyle=function(a){this.path=this.paths[a]};
BCIcon.prototype.fireEvent=function(a){a.target=this;for(var b in this.listeners[a.type])a.listenerId=b,this.listeners[a.type][b][0].call(this.listeners[a.type][b][1],a)};BCIcon.prototype.addListener=function(a,b,d){void 0===this.listeners[a]&&(this.listeners[a]=[]);this.listeners[a].push([b,d]);return this.listeners[a].length-1};BCIcon.prototype.removeListener=function(a,b){delete this.listeners[a][b]};$(function(){var a=$("<div></div>").attr({id:"debug-wrapper",width:800}).css({width:800,margin:20});a.bind("mousedown",function(){return!1});$("#page").append(a);$.getScript("js/lib/jquery-ui-1.8.17.custom.min.js").done(function(){var b=$("<div></div>").attr({id:"debug-scoring"});b.append($("<p></p>").append($("<label></label>").attr({"for":"debug-score-input"}).text("Scoring Threshold")).append($("<input></input>").attr({type:"text",id:"debug-score-input",value:"10"})).append($("<div></div>").attr({id:"debug-score-slider",
width:300}).slider({min:1,max:100,value:10,slide:function(a,b){$("#debug-score-input").val(b.value);folder.THRESHOLD=b.value;foldrecalcneeded=!0}})));$("#debug-score-input").val($("#debug-score-slider").slider("value"));a.append(b)}).fail(function(){console.log("Could not load jquery UI")})});function FitchCalculator(){this.GAP_EXT=-1;this.GAP_OPEN=-4;this.CHARS={T:1,A:2,G:4,C:8,".":16};this.CHARS_INDEX={T:0,A:1,G:2,C:3,".":4};this.RCHARS=["T","A","G","C","."];this.SCORE_MATRIX={A:{A:1,C:-1,G:-1,T:-1,".":-1},C:{A:-1,C:1,G:-1,T:-1,".":-1},G:{A:-1,C:-1,G:1,T:-1,".":-1},T:{A:-1,C:-1,G:-1,T:1,".":-1},".":{A:-1,C:-1,G:-1,T:-1,".":0}};this.GAP_MATRIX={A:{A:0,C:0,G:0,T:0,".":1},C:{A:0,C:0,G:0,T:0,".":1},G:{A:0,C:0,G:0,T:0,".":1},T:{A:0,C:0,G:0,T:0,".":1},".":{A:1,C:1,G:1,T:1,".":0}}}
FitchCalculator.diffSeqs=function(){for(var a=0,b=0,d=0,c,e=0;e<fold.length;e++)c=this.diffMatrix[this.original.charAt(e)][fold.charAt(e)],a+=c[0],b+=c[1],d+=c[2];return{difference:a,extra:b,missing:d}};FitchCalculator.treeops={};FitchCalculator.treeops.findNode=function(a,b){return function c(a,b,g){if(a instanceof Object&&void 0!=a[0]){if(b.bind(g)(a))return a;var h=c(a[0],b,g);return null!=h?h:c(a[1],b,g)}return null}(a,b,this)};
FitchCalculator.treeops.findNthNode=function(a,b){return function c(a,f){if(a instanceof Object&&void 0!=a[0]){if(f.count==b)return a;f.count+=1;var g=c(a[0],f);return null!=g?g:c(a[1],f)}return null}(a,{count:0})};FitchCalculator.treeops.getNodeIndex=function(a,b){return function c(a,f){if(a instanceof Object&&void 0!=a[0]){if(a==b)return f.count;f.count+=1;var g=c(a[0],f);return null!=g?g:c(a[1],f)}return-1}(a,{count:0})};
FitchCalculator.buildTree=function btree(b,d){return b instanceof Array?[btree(b[0],d),btree(b[1],d)]:d.shift()};FitchCalculator.seqLength=function(a){return a instanceof Array?FitchCalculator.seqLength(a[0]):a.length};
FitchCalculator.prototype.getFinalTree=function(a,b){var d=function(a){a-=a>>1&1431655765;a=(a>>2&858993459)+(a&858993459);a=(a>>4)+a&252645135;a+=a>>8;return a+(a>>16)&63},c=function j(a,b,c,e){if(a instanceof Array){void 0==c.seq&&(c.seq=[],c.ancestor=[],c[0]={},c[1]={});var f=j(a[0],b,c[0],e[0]),a=j(a[1],b,c[1],e[1]);c.seq[b]=void 0==e.value||void 0==e.value[b]?0==(f&a)?f|a:f&a:1<<e.value[b];c.ancestor[b]=Math.min(d((c.seq[b]&-c.seq[b])-1),4);return c.seq[b]}void 0==c.seq&&(c.seq=[],c.ancestor=
[]);c.seq[b]=a;c.ancestor[b]=Math.min(d((a&-a)-1),4);return a};console.log(d(15));console.log(d(0));for(var e=[],f=FitchCalculator.seqLength(a),g=0;g<f;g++){var h=this.diffLocation(a,g);e[g]=h.tree}f=[];for(g=0;g<e.length;g++)c(e[g],g,f,b);c="";for(g=0;g<f.ancestor.length;g++)c+=this.RCHARS[f.ancestor[g]];(function k(a,b){if(a instanceof Array||a instanceof Object&&void 0!=a[0]){k(a[0],b);k(a[1],b);a.stringancestor="";for(var c=0;c<a.ancestor.length;c++)a.stringancestor+=b[a.ancestor[c]]}})(f,this.RCHARS);
g={match:0,mismatch:0,gap_ext:0,gap_open:0};e=this.scoreTreeAlignment.bind(this)(f,g);return{ancestor:c,score:e,info:g,tree:f}};FitchCalculator.prototype.scoreTreeAlignment=function rec(b,d){if(b instanceof Object&&void 0!=b[0]){var c,e=0;c=0+rec.bind(this)(b[0],d);c+=rec.bind(this)(b[1],d);e+=this.scoreAlignment(b.ancestor,b[0].ancestor,d);e+=this.scoreAlignment(b.ancestor,b[1].ancestor,d);b.score=c+e;return c+e}return 0};
FitchCalculator.prototype.scoreAlignment=function(a,b,d){for(var c=0,e=!1,f=0,g=!0,h=0;h<a.length;h++)1==this.GAP_MATRIX[this.RCHARS[a[h]]][this.RCHARS[b[h]]]?g||(e?(c+=this.GAP_EXT,d.gap_ext+=1,f++):(c+=this.GAP_OPEN,e=!0,d.gap_open+=1,f=1)):(g=e=!1,c+=this.SCORE_MATRIX[this.RCHARS[a[h]]][this.RCHARS[b[h]]],0<this.SCORE_MATRIX[this.RCHARS[a[h]]][this.RCHARS[b[h]]]?d.match+=1:d.mismatch+=1);e&&(c-=(f-1)*this.GAP_EXT+this.GAP_OPEN,d.gap_ext-=f-1,d.gap_open-=1);return c};
FitchCalculator.prototype.diffLocation=function(a,b){var d=[0],c=this.extractLocation(a,b);return{ancestor:function f(a,b){if(a instanceof Array){var c=f(a[0],b),d=f(a[1],b);0==(c&d)?(b[0]++,a.seq=c|d):a.seq=c&d;return a.seq}return a}(c,d),parsimony:d[0],tree:c}};FitchCalculator.prototype.extractLocation=function(a,b){return a instanceof Array?[this.extractLocation(a[0],b),this.extractLocation(a[1],b)]:this.CHARS[a.charAt(b)]};var fitch=new FitchCalculator;
function DumpObjectIndented(a,b){var d="";null==b&&(b="");for(var c in a){var e=a[c];"string"==typeof e?e="'"+e+"'":"object"==typeof e&&(e instanceof Array?e="[ "+e+" ]":(e=DumpObjectIndented(e,b+"  "),e="\n"+b+"{\n"+e+"\n"+b+"}"));d+=b+"'"+c+"' : "+e+",\n"}return d.replace(/,\n$/,"")};function FoldCalculator(a){this.SHARP=4;this.THRESHOLD=10;this.p={A:{A:0,C:0,G:0,U:2,".":0},C:{A:0,C:0,G:4,U:0,".":0},G:{A:0,C:4,G:0,U:1,".":0},U:{A:2,C:0,G:1,U:0,".":0},".":{A:0,C:0,G:0,U:0,".":0}};this.po={A:{A:0,C:0,G:0,U:1,".":0},C:{A:0,C:0,G:1,U:0,".":0},G:{A:0,C:1,G:0,U:0,".":0},U:{A:1,C:0,G:0,U:0,".":0},".":{A:0,C:0,G:0,U:0,".":0}};this.diffMatrix={"<":{"<":[0,0,0],">":[1,0,0],".":[0,0,1]},">":{"<":[1,0,0],">":[0,0,0],".":[0,0,1]},".":{"<":[0,1,0],">":[0,1,0],".":[0,0,0]}};this.original=a.fold;
this.sequences=a.sequences}FoldCalculator.prototype.diffOriginal=function(a){for(var b=0,d=0,c=0,e,f=0;f<a.length;f++)e=this.diffMatrix[this.original.charAt(f)][a.charAt(f)],b+=e[0],d+=e[1],c+=e[2];return{difference:b,extra:d,missing:c}};FoldCalculator.prototype.score=function(){return this.foldAll(this.sequences,this.p)};FoldCalculator.prototype.setOriginal=function(a){this.original=a};FoldCalculator.prototype.setAll=function(a){this.original=a.fold;this.sequences=a.sequences};
FoldCalculator.prototype.setSeqs=function(a){this.sequences=a};FoldCalculator.prototype.getOriginal=function(){return this.original};FoldCalculator.sums=function(a,b,d,c){for(var e=0,f=0;f<d.length;f++)e+=c[d[f].charAt(a)][d[f].charAt(b)];return e};
FoldCalculator.prototype.backtrack=function(a,b,d,c,e){var f;f=c[b*d+a];0-this.THRESHOLD<=f&&-1>=f?(console.log("go neg"),e[a]=".",e[b]=".",this.backtrack(a+1,b-1,d,c,e)):0>f?(e[a]="<",e[b]=">",this.backtrack(a+1,b-1,d,c,e)):a<=f&&f+1<=b&&(this.backtrack(a,f,d,c,e),this.backtrack(f+1,b,d,c,e))};
FoldCalculator.prototype.foldAll=function(a,b){for(var d={},c=a[0].length,e=Array(c*c),f=0;f<c;f++)e[f*c+f]=0;for(f=1;f<c;f++)e[f*c+f-1]=0;for(f=c-1;0<=f;f--)for(var g=f;g<c;g++)if(g-f<=this.SHARP)e[g*c+f]=-1,e[f*c+g]=0;else{var h=FoldCalculator.sums(f,g,a,b),i=e[(f+1)*c+g-1]+h;e[g*c+f]=-1-h;for(var j=f;j<g;j++)h=e[f*c+j]+e[(j+1)*c+g],h>i&&(i=h,e[g*c+f]=j);e[f*c+g]=i}d.score=e[c-1];g=[];this.backtrack(0,c-1,c,e,g);c="";for(f=0;f<g.length;f++)c=null!=g[f]?c+g[f]:c+".";d.fold=c;return d};$(function(){$("#stage-redirect").bind("keydown",function(a){if(13==(a.keyCode?a.keyCode:a.which?a.which:a.charCode)){var b=document.location.search.replace("?",""),d="";if(b){var b=b.split("&"),c;for(c in b)-1==b[c].indexOf("id")&&(d+=b[c]+"&")}d="?"+d+"id="+$(this).val();document.location.search=d;a.preventDefault();return!1}return!0})});function getSequences(a){var b="ajax/fetch.php?";args.space&&(b=b+"space="+args.space+"&");args.name&&(b=b+"name="+args.name+"&");b=args.id?b+"id="+args.id+"&":b+"id=3871&";$.getJSON(b,function(b){var c=parseInput(b);a(c,b)})}
function parseInput(a){var b=[];(function g(a,b){a instanceof Array?(g(a[0],b),g(a[1],b)):b.push(a)})(a,b);for(var a=Array(b.length),d=0;d<b.length;d++){a[d]=[];var c,e;for(e=c=0;c<b[d].length;c++,e++)switch(b[d].charAt(c)){case "A":a[d][e]={id:0,colCount:c};break;case "U":case "T":a[d][e]={id:1,colCount:c};break;case "C":a[d][e]={id:2,colCount:c};break;case "G":a[d][e]={id:3,colCount:c};break;default:e--}}return a};var Language={};
function setLanguage(a){a||(a="en-us");(function(a,d){$.getJSON(LANG_DIR+a+LANG_EXT,function(c){console.log(LANG_DIR+a+LANG_EXT);d(c)})})(a,function(a){LANG=a;console.log("lang set");$("label[for='stats-matches']").html(LANG.body.play.gameselect.game_board.field_9);$("label[for='stats-gapexts']").html(LANG.body.play.gameselect.game_board.field_12);$("label[for='stats-stage']").html(LANG.body.play.gameselect.game_board.field_3);$("label[for='stats-mismatches']").html(LANG.body.play.gameselect.game_board.field_10);$("label[for='stats-gaps']").html(LANG.body.play.gameselect.game_board.field_11);
$("label[for='stats-par']").html(LANG.body.play.gameselect.game_board.field_2);$("label[for='scores-best']").html(LANG.body.play.gameselect.game_board.field_4);$("label[for='scores-score']").html(LANG.body.play.gameselect.game_board.field_1);Language.data=a})}$(function(){setLanguage()});function MessageBox(a){this._area=$("#"+a);this._area.bind("mousedown",function(){return!1})}MessageBox.prototype.println=function(a){this._area.val(this._area.val()+a+"\n");this._area.scrollTop(this._area.get(0).scrollHeight);return this};MessageBox.prototype.append=function(a){this._area.val(this._area.val()+a);return this};MessageBox.prototype.clear=function(){this._area.val("");return this};MessageBox.prototype.setText=function(a){this._area.val(a);console.log(this._area.val());return this};
MessageBox.prototype.getText=function(){return this._area.val()};function ColourConversion(){return!0}ColourConversion.rgbToRgbaString=function(a,b){return"rgba("+~~(a[0]+0.5)+","+~~(a[1]+0.5)+","+~~(a[2]+0.5)+","+b+")"};ColourConversion.rgbToHsl=function(a,b,d){var a=a/255,b=b/255,d=d/255,c=Math.max(a,b,d),e=Math.min(a,b,d),f,g=(c+e)/2;if(c==e)f=e=0;else{var h=c-e,e=0.5<g?h/(2-c-e):h/(c+e);switch(c){case a:f=(b-d)/h+(b<d?6:0);break;case b:f=(d-a)/h+2;break;case d:f=(a-b)/h+4}f/=6}return[f,e,g]};
ColourConversion.hslToRgb=function(a,b,d){if(0==b)d=b=a=d;else var c=function(a,b,c){0>c&&(c+=1);1<c&&(c-=1);return c<1/6?a+6*(b-a)*c:0.5>c?b:c<2/3?a+6*(b-a)*(2/3-c):a},e=0.5>d?d*(1+b):d+b-d*b,f=2*d-e,d=c(f,e,a+1/3),b=c(f,e,a),a=c(f,e,a-1/3);return[255*d,255*b,255*a]};
function ScoreBar(a){this.canvas=a;this.ctx=a.getContext("2d");this.currentScore=10;this.parScore=this.bestScore=0;this.params={animate:{from:{left:0,right:0,grid:10,bestScore:0,parScore:0,currentScore:0},to:{left:0,right:0,grid:10,bestScore:0,parScore:0,currentScore:0},current:{left:0,right:0,grid:10,bestScore:0,parScore:0,currentScore:0},interval:20,duration:500,handle:null,start:null,circIn:function(a){return 1-Math.sin(Math.acos(a))},circOut:function(a){return Math.sin(Math.acos(1-a))},circInOut:function(a){return 0.5>
a?0.5-Math.sin(Math.acos(2*a))/2:0.5+Math.sin(Math.acos(2-2*a))/2},step:function(a,d){d.animate.current.left=d.animate.from.left+(d.animate.to.left-d.animate.from.left)*a;d.animate.current.right=d.animate.from.right+(d.animate.to.right-d.animate.from.right)*a;d.animate.current.currentScore=d.animate.from.currentScore+(d.animate.to.currentScore-d.animate.from.currentScore)*a;d.animate.current.bestScore=d.animate.from.bestScore+(d.animate.to.bestScore-d.animate.from.bestScore)*a;d.animate.current.parScore=
d.animate.from.parScore+(d.animate.to.parScore-d.animate.from.parScore)*a;d.animate.current.grid=Math.pow(10,Math.floor(Math.log(d.animate.current.right-d.animate.current.left)/Math.log(10)-0.4))}},barHeight:0.4,leftBlank:100,rightBlank:100,colours:{gridLine:"rgba(200,200,200,0.3)",gridText:"rgba(200,200,200,0.9)",bestScoreLine:"rgb(120,250,120)",parScoreLine:"rgb(120,120,250)",bestScoreText:"rgb(120,250,120)",parScoreText:"rgb(120,120,250)",parBackground:"",barLow:[0,1,0.5],barMid:[0.2,1,0.5],barHigh:[0.44,
1,0.5],barRange:30,barAlpha:0.9,barTextFill:"white",barTextShadow:"rgba(0,0,0,0.9)",scoreText:"rgba(220,220,220,0.9)"}};this.listeners={"best-click":[]};this.params.animate.draw=this.draw;return!0}ScoreBar.alignToPixel=function(a){return~~a+0.5};
ScoreBar.prototype.getBarColour=function(a){void 0===a&&(a=this.params.animate.current.currentScore);var b=this.params.colours.barRange,b=Math.abs(a-this.parScore)/b;1<b&&(b=1);var d=this.params.colours.barMid,c=this.params.colours.barLow;a>=this.parScore&&(c=this.params.colours.barHigh);return ColourConversion.rgbToRgbaString(ColourConversion.hslToRgb(b*(c[0]-d[0])+d[0],b*(c[1]-d[1])+d[1],b*(c[2]-d[2])+d[2]),this.params.colours.barAlpha)};
ScoreBar.prototype.draw=function(){"undefined"!==typeof resizeinfo&&resizeinfo.resize&&(this.canvas.width=resizeinfo.scorebar_width);var a=this.ctx,b=this.canvas.width,d=this.canvas.height,c=this.params.animate;a.save();a.setTransform(1,0,0,1,0,0);a.clearRect(0,0,b,d);a.restore();var b=b-(this.params.leftBlank+this.params.rightBlank),e=b/(c.current.right-c.current.left),f=Math.abs(Math.min(c.current.left,0))/(c.current.right-c.current.left)*b+this.params.leftBlank;a.font="10pt sans-serif";a.textBaseline=
"bottom";a.textAlign="center";a.strokeStyle=this.params.colours.gridLine;a.fillStyle=this.params.colours.gridText;a.lineWidth=1;a.beginPath();for(var g=f;g<=this.canvas.width;)a.moveTo(ScoreBar.alignToPixel(g),0),a.lineTo(ScoreBar.alignToPixel(g),d),a.fillText(""+Math.round(10*((g-f)/e))/10,g,d),g+=c.current.grid*e;for(g=f;0<=g;)a.moveTo(ScoreBar.alignToPixel(g),0),a.lineTo(ScoreBar.alignToPixel(g),d),a.fillText(Math.round(10*((g-f)/e))/10,g,d),g-=c.current.grid*e;a.closePath();a.stroke();g=this.params.animate.current.currentScore*
e;a.fillStyle=this.getBarColour();a.textBaseline="middle";c=ScoreBar.getRect.call(this,this.params.animate.current.currentScore,e,f);a.beginPath();a.rect(c.left,c.top,c.width,c.height);a.closePath();a.fill();a.fillStyle=this.params.colours.barTextFill;a.lineWidth=2;a.save();a.shadowColor=this.params.colours.barTextShadow;a.shadowOffsetX=a.shadowOffsetY=0;a.shadowBlur=2;a.fillText(Math.round(this.params.animate.current.currentScore),g/2+f,d/2);a.restore();g=ScoreBar.alignToPixel(f+this.params.animate.current.bestScore*
e);a.textBaseline="top";a.textAlign="left";a.fillStyle=this.params.colours.bestScoreText;a.fillText("Best: "+Math.round(this.params.animate.current.bestScore),b+this.params.leftBlank+10,0);a.beginPath();a.moveTo(g,0);a.lineTo(g,d);a.closePath();a.strokeStyle=this.params.colours.bestScoreLine;a.stroke();g=ScoreBar.alignToPixel(f+this.params.animate.current.parScore*e);a.textBaseline="middle";a.fillStyle=this.params.colours.parScoreText;a.fillText("Par: "+Math.round(this.params.animate.current.parScore),
b+this.params.leftBlank+10,d/2);a.beginPath();a.moveTo(g,0);a.lineTo(g,d);a.closePath();a.strokeStyle=this.params.colours.parScoreLine;a.stroke();a.save();a.font="22pt sans-serif";a.fillStyle=this.params.colours.scoreText;a.textAlign="center";a.textBaseline="middle";a.fillText(Math.round(this.params.animate.current.currentScore),this.params.leftBlank/2,d/2);a.restore()};
ScoreBar.getRect=function(a,b,d){var c={},e=this.canvas.height;c.top=e*(1-this.params.barHeight)/2;c.height=this.params.barHeight*e;c.left=Math.min(a*b+d,d);c.width=Math.abs(a*b);return c};
ScoreBar.prototype.recalc=function(){var a=1.2*Math.min(this.currentScore,this.bestScore,this.parScore),b=1.2*Math.max(this.currentScore,this.bestScore,this.parScore);0<a&&(a=0);0>b&&(b=0);if(10>b-a)var d=5-(b-a)/2,b=b+d,a=a-d;this.params.animate.from.left=this.params.animate.current.left;this.params.animate.from.right=this.params.animate.current.right;this.params.animate.from.grid=this.params.animate.current.grid;this.params.animate.from.currentScore=this.params.animate.current.currentScore;this.params.animate.from.bestScore=
this.params.animate.current.bestScore;this.params.animate.from.parScore=this.params.animate.current.parScore;this.params.animate.to.left=a;this.params.animate.to.right=b;this.params.animate.to.grid=Math.pow(10,Math.floor(Math.log(b-a)/Math.log(10))-2);this.params.animate.to.currentScore=this.currentScore;this.params.animate.to.bestScore=this.bestScore;this.params.animate.to.parScore=this.parScore;(function(a){var b=a.params.animate;null!=b.handle&&(clearInterval(b.handle),b.handle=null);b.start=new Date;
b.handle=setInterval(function(){var d=(new Date-b.start)/b.duration;d>1&&(d=1);b.step(b.circInOut(d),a.params);a.draw();if(d==1){clearInterval(b.handle);b.handle=null}},b.interval)})(this)};ScoreBar.prototype.setScores=function(a,b){b="undefined"!==typeof b?b:!0;void 0!==a.score&&this.setScore(a.score,!1);void 0!==a.best&&this.setBest(a.best,!1);void 0!==a.par&&this.setPar(a.par,!1);b&&this.recalc()};
ScoreBar.prototype.setScore=function(a,b){b="undefined"!==typeof b?b:!0;this.currentScore=a;a>this.bestScore&&this.setBest(a,!1);b&&this.recalc()};ScoreBar.prototype.setBest=function(a,b){this.bestScore=a;("undefined"!==typeof b?b:1)&&this.recalc()};ScoreBar.prototype.setPar=function(a,b){this.parScore=a;("undefined"!==typeof b?b:1)&&this.recalc()};
ScoreBar.prototype.fireEvent=function(a){a.target=this;for(var b in this.listeners[a.type])a.listenerId=b,this.listeners[a.type][b][0].call(this.listeners[a.type][b][1],a)};ScoreBar.prototype.addListener=function(a,b,d){void 0===this.listeners[a]&&(this.listeners[a]=[]);this.listeners[a].push([b,d]);return this.listeners[a].length-1};ScoreBar.prototype.removeListener=function(a,b){delete this.listeners[a][b]};var pos=[],ctx,canvas,tcanvas,tctx,viewport,vctx,vp,multisel,originaltree,ancestorpos=[],currenttree,overridetree,currentancestor,currentancestorn,globalredraw={fitch:!1},bestscore=-1E4,drawThread,calcThread,sb,bc,resetting=!1,resizeinfo={},msg,fitchrecalcneeded=!1;$(function(){getSequences(init)});
function reset(a,b){if(!resetting){resetting=!0;clearInterval(drawThread);clearInterval(calcThread);pos=[];multisel=null;originaltree=b;ancestorpos=[];globalredraw={fitch:!1};currenttree=null;bestscore=-1E4;for(var d=0;d<a.length;d++)pos[d]=[],createRow(d,d*G_H,a[d]),finalize(d);vp=[];fitchCalculator=new FitchCalculator;originaltree=b;$(document).unbind();canvas=$("#drawing-area").unbind().get(0);canvas.width=V_W;canvas.height=V_H;ctx=canvas.getContext("2d");tcanvas=$("#tree-area").unbind().get(0);
tcanvas.width=T_W;tcanvas.height=T_H;tctx=tcanvas.getContext("2d");viewport=$("#viewport").unbind().get(0);viewport.width=VP_W;viewport.height=VP_H;vctx=viewport.getContext("2d");d=$("#scorebar-area").unbind().get(0);d.width=SB_W;d.height=SB_H;sb=new ScoreBar(d);sb.setScores({score:0,best:0,par:0});d=$("#buttoncolumn-area").unbind().get(0);d.width=BC_W;d.height=BC_H;bc=new ButtonColumn(d);bc.draw();setDrag();setViewportDrag();recalc();resetOverrideTree();vp.redraw=!0;pos.redraw=!0;drawThread=setInterval(draw,
33);fitchrecalcneeded=!0;recalcFitch();calcThread=setInterval(recalcFitch,400);resetting=!1}}function init(a,b){loadImages(function(){reset(a,b)})}
function loadImages(a){function b(){c.count<e?(console.log("still waiting"),setTimeout(b,20)):(console.log("images loaded"),a())}for(var d=function(a,b,c){var d=new Image;d.onload=function(){c.count+=1;b.push(this)};d.onerror=function(){c.count+=1};d.src=a},c={count:0},e=0,f=0;f<T_IMAGES_NAMES.length;f++)d(T_IMAGES_DIR+T_IMAGES_NAMES[f],T_IMAGES,c),e++;setTimeout(b,0)}
function findMaxLength(){for(var a=0,b=0;b<pos.length;b++)pos[b][pos[b].length-1].left>a&&(a=pos[b][pos[b].length-1].left);a=Math.ceil(a/G_W+1);console.log("max "+a);return a}function GameState(a,b){this.stage=a;this.tree=b;this.score=sb.currentScore}function getCurrentState(){var a=extractCurrentTree();return new GameState(args.id,a)}function loadState(a){args.id=a.stage;var b=parseInput(a.tree);reset(b,a.tree)}
function extractCurrentTree(){for(var a=Array(pos.length),b=findMaxLength(),d=["A","T","C","G"],c=0;c<pos.length;c++){var e=Array(b),f;for(f=0;f<b;f++)e[f]=".";for(f=0;f<pos[c].length;f++)e[~~((pos[c][f].left+G_W/2)/G_W)]=d[pos[c][f].kind];a[c]=e.join("")}return FitchCalculator.buildTree(originaltree,a)}
function recalcFitch(){if(fitchrecalcneeded){fitchrecalcneeded=!1;var a=extractCurrentTree(),a=fitch.getFinalTree(a,overridetree);currentancestor?(currentancestorn=FitchCalculator.treeops.getNodeIndex(currenttree,currentancestor),0>currentancestorn&&(currentancestorn=0)):currentancestorn=0;currentancestor=FitchCalculator.treeops.findNthNode(a.tree,currentancestorn);createAncestorRow(currentancestor.stringancestor);$("#stats-matches").text(a.info.match);$("#stats-gapexts").text(a.info.gap_ext);$("#stats-mismatches").text(a.info.mismatch);
$("#stats-gaps").text(a.info.gap_open);$("#scores-score").text(a.score);sb.setScore(a.score);if(a.score>bestscore){$("#scores-best").text(a.score);bestscore=a.score;var b=localStorage.getItem(args.id+"-Best");b&&JSON.parse(b).score<bestscore&&(b=getCurrentState(),console.log(b),localStorage.setItem(args.id+"-Best",JSON.stringify(b)),bc.setScoreForState("Best",b.score))}currenttree=a.tree;pos.redraw=!0;globalredraw.fitch=!0}}
function createAncestorRow(a){var b=[],d=[],c,e;for(e=c=0;c<a.length;c++,e++)switch(a.charAt(c)){case "A":b[e]={id:0,colCount:c};break;case "U":case "T":b[e]={id:1,colCount:c};break;case "C":b[e]={id:2,colCount:c};break;case "G":b[e]={id:3,colCount:c};break;default:e--}for(c=0;c<b.length;c++)3<b[c].id||(d[c]=[],d[c].row=V_ANCESTOR_ROW,d[c].left=b[c].colCount*G_W,d[c].top=V_ANCESTOR_ROW*G_H,d[c].redraw=!0,d[c].kind=b[c].id);ancestorpos=d}
function parseFoldOutput(a){for(var b=[],d=[],c=0,e=0;c<a.length;c++)switch(a.charAt(c)){case "<":d.push(c);break;case ">":b[e++]={"0":d.pop(),1:c}}b.sort(function(a,b){return a[0]-b[0]});return b}
function setDrag(){var a=null,b=0,d=!1,c="",e;$(document).mousedown(function(e){console.log(c);if("select"!=c){var g=$(canvas).offset(),h=e.pageX-g.left-S_MINX,i=e.pageY-g.top-S_MINY,j=~~(i/G_H);a=null;d=!0;if(j!=V_ANCESTOR_ROW){if(0<=j&&j<pos.length)for(e=0;e<pos[j].length;e++)if(pos[j][e].left+G_W>h&&pos[j][e].left<h){a=pos[j][e];a.drag=!0;b=h-pos[j][e].left;if(multisel){multisel.x=h;multisel.y=i;for(e=0;e<pos.length;e++)for(g=0;g<pos[e].length;g++)pos[e][g].selected&&(pos[e][g].drag=!0,pos[e][g].oldleft=
pos[e][g].left)}break}null==a&&(b=h);c="main"}else{for(e=0;e<ancestorpos.length;e++)if(ancestorpos[e].left+G_W>h&&ancestorpos[e].left<h){$("#ancestor-selection-box").css({top:ancestorpos[e].top+g.top-B_W,left:ancestorpos[e].left+g.left+S_MINX-B_W}).show();break}c="ancestor-change"}}});$(document).mouseup(function(b){d=!1;switch(c){case "main":if(null!=a){a.drag=!1;if(multisel)for(b=0;b<pos.length;b++)finalize(b);else finalize(a.row);resetOverrideTree();a=null}else{for(b=0;b<pos.length;b++)for(var g=
0;g<pos[b].length;g++)pos[b][g].selected=!1,pos[b][g].drag=!1;multisel=null;c="";pos.redraw=!0}break;case "viewport":S_MINX=~~S_MINX;vp.redraw=!0;pos.redraw=!0;break;case "select":$("#selection-box").hide();multisel.state="selected";c="";break;case "ancestor-change":var b=ancestorGetDistances(b.pageX,b.pageY),g=$(canvas).offset(),h=$("#ancestor-selection-box").offset();$("#ancestor-selection-box").hide();var i={top:1,left:0,bottom:3,right:2};setOverride(currentancestor,~~((h.left-g.left-S_MINX+G_W)/
G_W),0.7<b[b.dir]?i[b.dir]:4);fitchrecalcneeded=!0;e=null;c=""}});$(document).mousemove(function(e){0===e.which&&(d=!1);if(d)switch(c){case "main":if(null!=a){var g=e.pageX-$(canvas).offset().left;if(multisel){for(var g=multisel.x+S_MINX-g,h=0;h<pos.length;h++)for(var i=0;i<pos[h].length;i++)pos[h][i].selected&&(pos[h][i].left=pos[h][i].oldleft-g);pos.redraw=!0}else a.left=g-S_MINX-b;fitchrecalcneeded=!0;recalc()}else g=e.pageX-$(canvas).offset().left,S_MINX=-(b-g),S_MINX=Math.min(Math.max(-S_W+V_W,
S_MINX),0),VP_VP_LEFT=-(S_MINX/G_W*VP_B_W),pos.redraw=!0;break;case "ancestor-change":g=$(canvas).offset();ancestorSetBorderColours(ancestorGetDistances(e.pageX,e.pageY));break;case "viewport":g=e.pageX-$(viewport).offset().left,VP_VP_LEFT=Math.min(Math.max(0,g-VP_VP_W/2),VP_W-VP_VP_W),S_MINX=-(VP_VP_LEFT/VP_B_W*G_W),vp.redraw=!0,pos.redraw=!0}else switch(c){case "select":if("start"==multisel.state){multisel.p2.x=e.pageX;multisel.p2.y=e.pageY;var h=multisel.p1.y>multisel.p2.y?multisel.p2.y:multisel.p1.y,
e=multisel.p1.x>multisel.p2.x?multisel.p2.x:multisel.p1.x,j=Math.abs(multisel.p1.x-multisel.p2.x),i=Math.abs(multisel.p1.y-multisel.p2.y),g=$(canvas).offset(),k=~~((h-g.top-S_MINY)/G_H),l=~~((h+i-g.top-S_MINY)/G_H);a.offset({top:h,left:e}).width(j).height(i);for(h=0;h<pos.length;h++)for(i=0;i<pos[h].length;i++)pos[h][i].selected=!1;for(h=0<=k?k:0;h<pos.length&&h<=l;h++){for(i=0;i<pos[h].length&&!(pos[h][i].left+g.left+S_MINX+G_W>e);i++);for(;i<pos[h].length&&pos[h][i].left+g.left+S_MINX<j+e;i++)pos[h][i].selected=
!0}pos.redraw=!0}}});$(document).dblclick(function(b){if(multisel){for(b=0;b<pos.length;b++)for(var d=0;d<pos[b].length;d++)pos[b][d].selected=!1,pos[b][d].drag=!1;multisel=null;c="";pos.redraw=!0}else a=$("#selection-box").show().offset({top:b.pageY,left:b.pageX}).width(0).height(0),c="select",multisel={state:"start",p1:{x:b.pageX,y:b.pageY},p2:{x:b.pageX,y:b.pageY}}});$(viewport).mousedown(function(a){if("select"!=c)return a=a.pageX-$(viewport).offset().left,d=!0,b=a,c="viewport",!1});$(tcanvas).mousemove(function(a){var b=
$(tcanvas).offset(),a=function i(a,b,c){if(a instanceof Object&&void 0!=a[0]){if(a.ancestorlocation&&a.ancestorlocation.left<b&&a.ancestorlocation.left+a.ancestorlocation.width>b&&a.ancestorlocation.top<c&&a.ancestorlocation.top+a.ancestorlocation.height>c)return a;var d=i(a[0],b,c);return null!=d?d:d=i(a[1],b,c)}return null}(currenttree,a.pageX-b.left,a.pageY-b.top);null!=a?a!=currentancestor&&(e=currentancestor,currentancestor=a,drawTree(tctx),createAncestorRow(currentancestor.stringancestor),pos.redraw=
!0):(currentancestor!=e&&null!=e&&(currentancestor=e,drawTree(tctx),createAncestorRow(currentancestor.stringancestor),pos.redraw=!0),e=null)});$(tcanvas).mousedown(function(){e=currentancestor})}function setOverride(a,b,d){console.log(b,d);a=function e(a,b,d){if(a instanceof Object&&void 0!=a[0]){if(d==a)return b;var i=e(a[0],b[0],d);return null!=i?i:i=e(a[1],b[1],d)}return null}(currenttree,overridetree,a);null!=a&&(a.value[b]=d)}
function resetOverrideTree(){var a=FitchCalculator.seqLength(originaltree)+20;overridetree=FitchCalculator.buildTree(originaltree,Array(pos.length));(function d(a,e){a instanceof Object&&void 0!=a[0]&&(d(a[0],e),d(a[1],e),a.value=Array(e))})(overridetree,a);overridetree.set=!1}
function ancestorGetDistances(a,b){var d=$("#ancestor-selection-box").offset(),c={top:-0.2,left:-0.2,bottom:-0.2,right:-0.2},e=a-(d.left+1.5*B_W),f=b-(d.top+1.5*B_H),d=-Math.atan2(f,e),e=Math.min(Math.max(Math.sqrt(e*e+f*f)/(2*B_W),0.2),1);Math.abs(d)<Math.PI/4?(c.right=1,c.dir="right"):Math.abs(d)>0.75*Math.PI?(c.left=1,c.dir="left"):0<d?(c.top=1,c.dir="top"):(c.bottom=1,c.dir="bottom");c.top=c.top*e+0.4;c.left=c.left*e+0.4;c.right=c.right*e+0.4;c.bottom=c.bottom*e+0.4;return c}
function ancestorSetBorderColours(a){$("#ancestor-selection-box").css({"border-top-color":B_COLOUR_A[0]+a.top+")","border-left-color":B_COLOUR_A[1]+a.left+")","border-bottom-color":B_COLOUR_A[2]+a.bottom+")","border-right-color":B_COLOUR_A[3]+a.right+")"})}function setViewportDrag(){}
function createRow(a,b,d){if(void 0!=args.rand)var c=generateRandomRowPositions(d.length,S_W-G_W);for(var e=0;e<d.length;e++)3<d[e].id||(pos[a][e]=[],pos[a][e].row=a,pos[a][e].left=args.rand?S_MINX+c[e]:d[e].colCount*G_W,pos[a][e].top=b,pos[a][e].redraw=!0,pos[a][e].kind=d[e].id)}function generateRandomRowPositions(a,b){for(var d=[],c=0;c<a;c++)d[c]=Math.floor(Math.random()*b);return d=d.sort(function(a,b){return a-b})}
function finalize(a){for(var b=0;b<pos[a].length;b++)pos[a][b].left=~~((pos[a][b].left+G_W/2)/G_W)*G_W,pos[a][b].redraw=!0}
function recalc(){var a=!1,b=0,d,c;for(d=0;d<pos.length;d++){a=!1;b=S_W;for(c=pos[d].length-1;0<=c;c--)pos[d][c].drag?(a=!0,pos[d][c].redraw=!0):a&&pos[d][c].left>b-G_W&&(pos[d][c].left=b-G_W,pos[d][c].redraw=!0),b=pos[d][c].left;a=!1;b=-G_W;for(c=0;c<pos[d].length;c++)pos[d][c].drag?(a=!0,pos[d][c].redraw=!0):a&&pos[d][c].left<b+G_W&&(pos[d][c].left=b+G_W,pos[d][c].redraw=!0),b=pos[d][c].left;b=-G_W;for(c=0;c<pos[d].length;c++)pos[d][c].left<b+G_W&&(pos[d][c].left=b+G_W,pos[d][c].redraw=!0),b=pos[d][c].left;
b=S_W;for(c=pos[d].length-1;0<=c;c--)pos[d][c].left>b-G_W&&(pos[d][c].left=b-G_W,pos[d][c].redraw=!0),b=pos[d][c].left}}
function drawRow(a,b,d){for(var c=0;c<pos[b].length;c++)pos[b][c].left+S_MINX+B_XOFFSET>=-G_W&&pos[b][c].left+S_MINX+B_XOFFSET+G_W<=V_W+G_W&&(d?(a.fillStyle=B_COLOUR_H[pos[b][c].kind],a.fillRect(pos[b][c].left+S_MINX+B_XOFFSET,pos[b][c].top+S_MINY+B_YOFFSET,B_W,B_H),a.strokeStyle=BS_COLOUR_H[pos[b][c].kind],a.strokeRect(pos[b][c].left+S_MINX+B_XOFFSET,pos[b][c].top+S_MINY+B_YOFFSET,B_W,B_H)):(a.fillStyle=pos[b][c].selected?B_COLOUR_S[pos[b][c].kind]:B_COLOUR[pos[b][c].kind],a.fillRect(pos[b][c].left+
S_MINX+B_XOFFSET,pos[b][c].top+S_MINY+B_YOFFSET,B_W,B_H))),pos[b][c].redraw=!1}function drawAncestorRow(a){for(var b=0;b<ancestorpos.length;b++)ancestorpos[b].left+S_MINX+B_XOFFSET>=-G_W&&ancestorpos[b].left+S_MINX+B_XOFFSET+G_W<=V_W+G_W&&(a.fillStyle=B_COLOUR[ancestorpos[b].kind],a.fillRect(ancestorpos[b].left+S_MINX+B_XOFFSET,ancestorpos[b].top+S_MINY+B_YOFFSET,B_W,B_H)),ancestorpos[b].redraw=!1}
function draw(){resizeinfo.resize&&(canvas.width=resizeinfo.canvas_width,viewport.width=resizeinfo.viewport_width,resizeinfo.resize=!1,pos.redraw=!0);if(pos.redraw){ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.restore();generateGrid(ctx);for(var a=0;a<pos.length;a++)drawRow(ctx,a);drawAncestorRow(ctx);pos.redraw=!1;drawViewport(!0)}else{var b=!1;ctx.save();for(a=0;a<pos.length;a++){var d;for(d=0;d<pos[a].length&&!pos[a][d].redraw;d++);d<pos[a].length&&
(ctx.setTransform(1,0,0,1,0,0),ctx.clearRect(0,G_H*a+S_MINY,V_W,G_H),b=!0,pos[a].redraw=!0)}ctx.restore();if(b){generateGrid(ctx);for(a=0;a<pos.length;a++)if(pos[a].redraw){for(d=0;d<pos[a].length;d++)pos[a][d].left+S_MINX+B_XOFFSET>=-G_W&&pos[a][d].left+S_MINX+B_XOFFSET+G_W<=V_W+G_W&&(ctx.fillStyle=pos[a][d].selected?B_COLOUR_S[pos[a][d].kind]:B_COLOUR[pos[a][d].kind],ctx.fillRect(pos[a][d].left+S_MINX+B_XOFFSET,pos[a][d].top+S_MINY+B_YOFFSET,B_W,B_H)),pos[a][d].redraw=!1;pos[a].redraw=!1}drawAncestorRow(ctx);
drawViewport(!0)}else drawViewport(!1)}globalredraw.fitch&&(drawTree(tctx),globalredraw.fitch=!1)}
function drawViewport(a){if(a||vp.redraw){vctx.save();vctx.setTransform(1,0,0,1,0,0);vctx.clearRect(0,0,viewport.width,viewport.height);vctx.restore();for(var b=a=0;b<pos.length;b++)for(var d=0;d<pos[b].length;d++)vctx.fillStyle=B_COLOUR[pos[b][d].kind],a=~~(pos[b][d].left/G_W),vctx.fillRect(a*VP_B_W,b*VP_B_H,VP_B_W,VP_B_H);vctx.fillStyle=VP_OVERLAY_COLOUR;vctx.fillRect(0,0,VP_VP_LEFT,VP_VP_H);vctx.fillRect(VP_VP_LEFT+VP_VP_W,0,VP_W-VP_VP_LEFT-VP_VP_W,VP_VP_H);vctx.strokeStyle=VP_BORDER_COLOUR;vctx.lineWidth=
VP_BORDER_WIDTH;vctx.strokeRect(VP_VP_LEFT,0,VP_VP_W,VP_VP_H);vp.redraw=!1}}function generateGrid(a){a.beginPath();for(var b=0;b<=G_ROW;b++)a.moveTo(-0.5,S_MINY+b*G_H+0.5),a.lineTo(V_W+0.5,S_MINY+b*G_H+0.5);for(var b=~~(V_W/G_W)+1,d=0;d<=b;d++)a.moveTo(S_MINX%G_W+d*G_W+0.5,S_MINY+0.5),a.lineTo(S_MINX%G_W+d*G_W+0.5,S_MINY+G_ROW*G_H-1+0.5);a.lineWidth=1;a.strokeStyle=G_COLOUR;a.stroke();a.closePath()}
function drawTree(a){var b=function g(b,c){b instanceof Object&&void 0!=b[0]&&(g(b[0],c),g(b[1],c),(!c&&b.node!=currentancestor||c&&b.node==currentancestor)&&a.rect(T_W-(b.depth*T_SIZE_H+T_RIGHT)-T_ANCESTOR_BUTTON_W/2,T_TOP+~~(b.height*T_SIZE_V)-T_ANCESTOR_BUTTON_H/2,T_ANCESTOR_BUTTON_W,T_ANCESTOR_BUTTON_H),b.node.ancestorlocation={top:T_TOP+~~(b.height*T_SIZE_V)-T_ANCESTOR_BUTTON_W/2,left:T_W-(b.depth*T_SIZE_H+T_RIGHT)-T_ANCESTOR_BUTTON_W/2,width:T_ANCESTOR_BUTTON_W,height:T_ANCESTOR_BUTTON_H})},
d=function h(b){b instanceof Object&&void 0!=b[0]&&(h(b[0]),h(b[1]),a.fillText(0<b.node.score?"+"+b.node.score:""+b.node.score,T_W-(b.depth*T_SIZE_H+T_RIGHT)-3,T_TOP+~~(b.height*T_SIZE_V)))},c={};(function i(a,b,c){if(a instanceof Object&&void 0!=a[0]){var d=0;b[0]={};b[1]={};var e=i(a[0],b[0],c),c=i(a[1],b[1],c),d=Math.max(e.depth,d),d=Math.max(c.depth,d);b.depth=d+1;b.height=(e.height+c.height)/2;b.from=e.height;b.to=c.height;b.node=a}else b.depth=0,b.height=c[0],c[0]+=1;return b})(currenttree,
c,[0]);a.save();a.setTransform(1,0,0,1,0,0);a.clearRect(0,0,tcanvas.width,tcanvas.height);a.restore();var e=a.createLinearGradient(T_W,0,T_W-T_BACKGROUND_GRID_W,0);e.addColorStop(0,G_COLOUR);e.addColorStop(1,G_COLOUR_A);a.strokeStyle=e;a.lineWidth=1;a.beginPath();for(e=0;e<=G_ROW;e++)a.moveTo(T_W-T_BACKGROUND_GRID_W+0.5,e*G_H+0.5),a.lineTo(T_W+0.5,e*G_H+0.5);a.closePath();a.stroke();(function j(b,c){b instanceof Object&&void 0!=b[0]?(j(b[0],b.depth,c),c=j(b[1],b.depth)):a.drawImage(T_IMAGES[c],0,
0,T_IMAGES[c].width,T_IMAGES[c].height,T_W-30,T_TOP+~~(b.height*T_SIZE_V)-T_IMAGES_DRAW_H/2,T_IMAGES_DRAW_W,T_IMAGES_DRAW_H);return c+1})(c,0);a.font="12px sans-serif";a.textBaseline="middle";a.textAlign="right";a.fillStyle=T_COLOUR;a.fillText("Ancestor",T_W-5,G_H*V_ANCESTOR_ROW+G_H/2);a.fillStyle=T_COLOUR;a.strokeStyle=T_COLOUR;a.beginPath();(function k(b,c){b instanceof Object&&void 0!=b[0]&&(k(b[0],b.depth),k(b[1],b.depth),a.moveTo(T_W-(b.depth*T_SIZE_H+T_RIGHT),T_TOP+~~(b.from*T_SIZE_V)),a.lineTo(T_W-
(b.depth*T_SIZE_H+T_RIGHT),T_TOP+~~(b.to*T_SIZE_V)));a.moveTo(T_W-(b.depth*T_SIZE_H+T_RIGHT),T_TOP+~~(b.height*T_SIZE_V));a.lineTo(T_W-(c*T_SIZE_H+T_RIGHT),T_TOP+~~(b.height*T_SIZE_V))})(c,8);a.closePath();a.lineWidth=T_THICKNESS;a.lineCap="square";a.stroke();a.fill();a.fillStyle=T_COLOUR;a.beginPath();b(c,!1);a.closePath();a.fill();a.fillStyle=T_COLOUR_S;a.beginPath();b(c,!0);a.closePath();a.fill();args.ui_showscore&&(a.font="10px sans-serif",a.textBaseline="bottom",a.textAlign="right",a.fillStyle=
T_COLOUR,d(c))};$(window).resize(function(){var a=0.8*$(window).width()-T_W-BC_W;a>SIZE_MAX_WIDTH?a=SIZE_MAX_WIDTH:a<SIZE_MIN_WIDTH&&(a=SIZE_MIN_WIDTH);V_W=a;VP_B_W=a/G_COL;SB_W=VP_W=a+T_W+BC_W;resizeinfo.resize=!0;resizeinfo.canvas_width=a;resizeinfo.viewport_width=a+T_W+BC_W;resizeinfo.scorebar_width=SB_W;sb&&sb.draw()});$(window).resize();
